development:
  adapter: postgresql
  encoding: unicode
  database: otacon_development

test:
  adapter: postgresql
  encoding: unicode
  database: otacon_test

production:
  adapter: postgresql
  encoding: unicode
  database: otacon_production
